[package]
name = "portunus-keycached"
version = "0.1.0"
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
