name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: fmt, build, clippy, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.17, 2024-06-12

      - name: Install stable toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # stable, 2024-06-13
        with:
          toolchain: stable

      # Use both `**/Cargo.lock` and `**/Cargo.toml` in cache key: While Cargo.lock is enough to
      # ensure that we clear the cache when dependencies change, we currently don't treat forgetting
      # to commit Cargo.lock as a failure. Changing Cargo.toml without bumping the dependencies may
      # clear the cache when it isn't necessary.
      - name: Use build cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2, 2024-03-19
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}

      - run: cargo fmt --all -- --check
      - run: cargo build --all-targets
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test --all-targets
